# Generated by Django 4.1.4 on 2022-12-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='имя файла')),
                ('file', models.FileField(upload_to='music_files/', verbose_name='файл')),
            ],
            options={
                'verbose_name': 'Музыкальный файл',
                'verbose_name_plural': 'Музыкальные файлы',
            },
        ),
    ]
